// Buffs e Debuffs predefinidos do sistema
// Campos opcionais: pvTemp (PV temporários), dorExtra (slots de dor extras)
const BUFFS_PREDEFINIDOS = [
  {
    id: "coragem",
    emoji: "🍺",
    nome: "Levanta Defunto",
    desc: "Vantagem em testes de Coragem",
    tipo: "positivo",
    vinheta: "buff",
  },
  {
    id: "vigor",
    emoji: "💪",
    nome: "Vigor",
    desc: "+1 em testes de Força",
    tipo: "positivo",
    vinheta: "buff",
  },
  {
    id: "velocidade",
    emoji: "💨",
    nome: "Aceleração",
    desc: "+1 de Movimento",
    tipo: "positivo",
    vinheta: "buff",
  },
  {
    id: "protecao",
    emoji: "🛡️",
    nome: "Proteção",
    desc: "Reduz 1 dano do próximo ataque",
    tipo: "positivo",
    vinheta: "buff",
  },
  {
    id: "foco",
    emoji: "🎯",
    nome: "Foco",
    desc: "Vantagem em testes de INT",
    tipo: "positivo",
    vinheta: "buff",
  },
  {
    id: "vidatemp2",
    emoji: "💚",
    nome: "Vitalidade",
    desc: "+2 PV Temporários",
    tipo: "positivo",
    vinheta: "buff",
    pvTemp: 2,
  },
  {
    id: "vidatemp4",
    emoji: "💖",
    nome: "Vitalidade Maior",
    desc: "+4 PV Temporários",
    tipo: "positivo",
    vinheta: "buff",
    pvTemp: 4,
  },
  {
    id: "resistencia",
    emoji: "🦴",
    nome: "Resistência",
    desc: "+2 slots de Dor",
    tipo: "positivo",
    vinheta: "buff",
    dorExtra: 2,
  },
  {
    id: "peledeaco",
    emoji: "🔩",
    nome: "Pele de Aço",
    desc: "+3 slots de Dor",
    tipo: "positivo",
    vinheta: "buff",
    dorExtra: 3,
  },
  {
    id: "envenenado",
    emoji: "☠️",
    nome: "Envenenado",
    desc: "-1 PV por turno",
    tipo: "negativo",
    vinheta: "veneno",
  },
  {
    id: "queimando",
    emoji: "🔥",
    nome: "Queimando",
    desc: "-1 PV por turno, pode se espalhar",
    tipo: "negativo",
    vinheta: "fogo",
  },
  {
    id: "congelado",
    emoji: "❄️",
    nome: "Congelado",
    desc: "-1 de Movimento",
    tipo: "negativo",
    vinheta: "gelo",
  },
  {
    id: "sangrando",
    emoji: "🩸",
    nome: "Sangrando",
    desc: "-1 PV no início do turno até medicina DT 6",
    tipo: "negativo",
    vinheta: "sangramento",
  },
  {
    id: "atordoado",
    emoji: "💫",
    nome: "Atordoado",
    desc: "Perde a próxima ação",
    tipo: "negativo",
    vinheta: "atordoado",
  },
  {
    id: "cego",
    emoji: "🙈",
    nome: "Cego",
    desc: "Desvantagem em ataques",
    tipo: "negativo",
    vinheta: "",
  },
  {
    id: "amedrontado",
    emoji: "😨",
    nome: "Amedrontado",
    desc: "Desvantagem em COR",
    tipo: "negativo",
    vinheta: "",
  },
  {
    id: "fraqueza",
    emoji: "😵",
    nome: "Fraqueza",
    desc: "-2 slots de Dor",
    tipo: "negativo",
    vinheta: "",
    dorExtra: -2,
  },
];
